book/urls.py
from django.urls import path
from book.views import BooksView, BooksDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView


app_name = 'books'

urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path("<int:id>/", BooksDetailView.as_view(), name='detail'),
    path("<int:id>/reviews", AddReviewView .as_view(), name='reviews'),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name='edit-review'),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name='delete-review'),
    
]

goodreader/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
   
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),
    
    path('users/', include('users.urls')),
    path('books/', include('book.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone



class Book(models.Model):
    title =models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_cover.jpg")
    
    def __str__(self):
        return self.title
    
    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    
    
class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)       
    
    def __str__(self):
        return f"{self.book} by {self.author.first_name} { self.author.last_name }"
    
    
class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    strts_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]        
    )
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f"{self.strts_given} stars for {self.book.title} by { self.user.username }"

book/forms.py
from django import forms
from .models import BookReview



class BookReviewForm(forms.ModelForm):
    strts_given = forms.IntegerField(min_value=1, max_value=5)
    
    class Meta:
        model = BookReview
        fields  = ('strts_given','comment')

book/views.py
from django.shortcuts import render,redirect
from django.views import View
from book.models import Book
from django.core.paginator import Paginator
from .forms import BookReviewForm
from .models import BookReview
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.contrib import messages

  
  
    
class BooksView(View):
    def get(self,request):
        books = Book.objects.all().order_by('id')
        
        search_query = request.GET.get('q' ,'')
        if search_query:
            books = books.filter(title__icontains=search_query)
        
        page_size = request.GET.get('page_size', 3)
       
         
        paginator = Paginator(books, page_size)        
        page_num = request.GET.get('page', 1)
        
        page_obj = paginator.get_page(page_num)        
        context = {
            'page_obj':page_obj,
            'search_query':search_query
            }
        
        
        
        return render(request,'books/list.html', context)
            
    
class BooksDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()
        context = {'book':book,'form':review_form }
        return render(request, 'books/detail.html', context)

    
class AddReviewView(LoginRequiredMixin,View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)
        
        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                strts_given=review_form.cleaned_data['strts_given'],
                comment=review_form.cleaned_data['comment']
            )
            
            return redirect(reverse("books:detail", kwargs={ "id":book.id }))
        
        context = {'book':book,'form':review_form }
        return render(request, 'books/detail.html', context)
    

class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)
        
        context = {
            'book':book,
            'review':review,
            'form':review_form
            }
        return render(request, 'books/edit_review.html', context)
    
    def post(self,request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)
        
        if review_form.is_valid():
            review_form.save() 
            
            return redirect(reverse("books:detail", kwargs={ "id":book.id }))
        
        context = {
            'book':book,
            'review':review,
            'form':review_form
            }
        return render(request, 'books/edit_review.html', context)


class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self,request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        context = {
            'book':book,
            'review':review
        }        
        return render(request, 'books/confirm_delete_review.html', context)  

    
class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
       book = Book.objects.get(id=book_id)
       review = book.bookreview_set.get(id=review_id)
       
       review.delete()
       messages.success(request, "You have successfully deleted this review")
       
       return redirect(reverse("books:detail", kwargs={ "id":book.id }))    
    

book/templates/books/confirm_delete_review.html
{% extends 'base.html' %}

{% block title %} Confirm Delete Reviews {% endblock %}


{% block content %}

<h3>Are you sure you want to delete this review ? </h3>
<p>
        <b>Book</b>: {{ book.title }}
</p>

<p>
    <b>Comment</b>: {{ review.comment }}
</p>

<a href="{% url 'books:delete-review' book.id review.id %}" class="btn btn-outline-danger">Yes</a> <a class="btn btn-outline-primary" href="{% url 'books:detail' book.id %}">No</a>

{% endblock %}

book/templates/books/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block title %} Book detail Page {% endblock %}

{% block content %}

    <div class="row mb-4">
        <div class="col-2">
            <img class="cover-pic" alt="cover image" src="{{ book.cover_picture.url }}">
        </div>

        <div class="col-6 ms-4">
            <h3>{{ book.title }}</h3>
            <span class="fst-italic">
                Authored by                
                {% for book_author in book.bookauthor_set.all %}
                    {% if forloop.last %}
                        <b>{{ book_author.author.full_name }}</b>
                    {% else %}
                        <b>{{ book_author.author.full_name }}</b>,
                    {% endif %}

                {% endfor %}
            </span>

            <p>
                {{ book.description }}
            </p>

        </div>
    </div>

    <div class="row mb-4">
        <div class="col-6">
            <form method="POST" action="{% url 'books:reviews' book.id  %}">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-success">Add Review</button>
            </form>            
        </div>
    </div>

    {% if book.bookreview_set.exists %}
        <h4>Reviews</h4> <hr>

        {% for review in book.bookreview_set.all %}
            <div class="row mb-3">
                <div class="col-1">
                    <img class="small-profile-pic" src="{{ review.user.profile_picture.url }}">
                </div>
                <div class="col-7">
                    <b>{{ review.user.username }}</b> rated it {{ review.strts_given}} stars <span class="fw-lighter">{{ review.created_at }}</span>

                    {% if review.user == request.user %}
                        <a href="{% url 'books:edit-review' book.id review.id %}"><i class="bi bi-pen"></i></a>
                        <a href="{% url 'books:confirm-delete-review' book.id review.id %}"><i class="bi bi-trash"></i></a>
                    {% endif %}
                    <p class="font-monospace mt-2 fs-8 ">{{review.comment}}</p>                    
                    
                </div>
            </div>
        {% endfor %}
    {% endif%}
    
    
{% endblock %}

book/templates/books/edit_review.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block title %} Edit review {% endblock %}

{% block content %}
<h3>Edit review</h3>
<div class="row mb-4">
    <div class="col-6">
        <form method="POST" action="{% url 'books:edit-review' book.id review.id  %}">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-success">Save</button>
        </form>        
    </div>
</div>

{% endblock  %}

book/templates/books/list.html
{% extends 'base.html'%}
    

    {% block title %} Book page {% endblock %}



{% block content %}
    <h1>Books</h1>
     <h1>Books  Books</h1>

    <div class="row mb-3">
        <div class="col-4">
            <form class="d-flex" method="GET">
                <input class="form-control me-2" type="text" name="q" placeholder="Search" value="{{search_query}}">
                <button class="btn btn-success">Search</button>
            </form>
        </div>
    </div>
 
    {% if page_obj %}
        {% for book in page_obj.object_list %}
            <div class="row mb-4">
                <div class="col-1">
                    <img class="cover-pic" src="{{ book.cover_picture.url }}">
                </div>
                <div class="col-6 ms-4">
                    <a href="{% url 'books:detail' book.id %}">{{ book.title }}</a>
                    <p>
                        {{ book.description }}
                    </p>
                </div>
            </div>            
            <br>        
        {% endfor %}


        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}
        
                <li class="page-item active">
                    <a href="#" class="page-link">{{ page_obj.number  }}</a>
                </li>
        
        
                {% if page_obj.has_next %}            
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
                {% endif %}
        
            </ul>   
        
        </nav>



    {% else %}
            No books found
    {% endif %}




    

{% endblock %}