book/urls.py
from django.urls import path
from book.views import BooksView, BooksDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView


app_name = 'books'

urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path("<int:id>/", BooksDetailView.as_view(), name='detail'),
    path("<int:id>/reviews", AddReviewView .as_view(), name='reviews'),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name='edit-review'),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name='delete-review'),
    
]

goodreader/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
   
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),
    
    path('users/', include('users.urls')),
    path('books/', include('book.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView,ProfileUpdateView



app_name = 'users'

urlpatterns = [  
    path('register/',RegisterView.as_view(), name='register'),
    path('login/',LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/',ProfileView.as_view(), name='profile'),
    path('profile/edit/',ProfileUpdateView.as_view(), name='profile-edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.jpg")

users/forms.py
from django import forms 
from users.models import CustomUser



class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username','first_name', 'last_name','email','password')
                   
        
    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
        
        
    
class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=128)
                

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username','first_name', 'last_name','email', 'profile_picture')
    

users/views.py
from django.shortcuts import render,redirect
from django.views import View
from users.models import CustomUser
from users.forms import UserCreateForm, UserLoginForm, UserUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages




class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        
        context = {
            'form':create_form
        }  
        return render(request, 'users/register.html',context)
    
    def post(self,request):
        create_form = UserCreateForm(data=request.POST)
        if create_form.is_valid():
            create_form.save()
              
            return redirect('users:login')
        else: 
            context = {
                'form':create_form
            }   
        return render(request, 'users/register.html', context)
  
    
class LoginView(View):
    def get(self, request):
        login_form = UserLoginForm()
        context =  {'form':login_form}
        return render(request,'users/login.html', context)
    
    def post(self, request):        
        login_form = AuthenticationForm(data=request.POST)
        
        if login_form.is_valid():
            user = login_form.get_user()
            login(request,user)
            messages.success(request, 'You have successully loged in')
            
            return redirect('books:list')
        else:        
        
            context =  {'form':login_form}
            
            return render(request,'users/login.html', context)
    
 
class ProfileView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('users:login')
          
       
        context = {'user':request.user}
        return render(request, 'users/profile.html', context) 
    
    

class LogoutView(LoginRequiredMixin,View):
    def get(self,request):
        logout(request)
        messages.info(request, 'You have successfully loged out')
        
        return redirect('landing_page')
    
    
class ProfileUpdateView(LoginRequiredMixin,View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        context = {'form': user_update_form}
        return render(request,"users/profile_edit.html",context)    
        
    def post(self,request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
            )
        
        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request,"You have successfully update your profile.")
            return redirect('users:profile')
        
        context = {'form':user_update_form}
        return render(request,"users/profile_edit.html", context) 
        
        

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    

{% block title %} Login {% endblock %}



{% block content %}
<h3>Login</h3>

<div class="row">
    <div class="col-4">
        <form method="POST" >
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary">Log in</button> <span class="ms-3">No account? Then, <a href="{%  url 'users:register'%}">get registered</a></span>
        </form>  
    </div>
</div>

   

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}


    {% block title %} Profile Page {% endblock %}

{% block content %}
        
    <div class="image d-flex flex-column justify-content-center align-items-center">
        <button class="btn btn-secondary">
            <img class="profile-pic" alt="Profile Picture" src="{{ user.profile_picture.url }}">
        </button>       
        <span class="name mt-3">{{user.first_name }} {{ user.last_name }}</span>
        <span class="idd">@{{ user.username }}</span>
        <span class="idd">{{ user.email }}</span>           
        <div class="d-flex mt-2"><a class="btn btn-dark " href="{% url 'users:profile-edit' %}">edit profile</a></div>
        <div class="px-2 rounded mt-2 date"><span class="join">Joined {{ user.date_joined | date:"M d,Y"}}</span></div>
   
    </div>

{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}

<h3>Edit Profile</h3>

<div class="row">
    <div class="col-4">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
        
            <button class="btn btn-primary">save changes</button>
        
        </form>

    </div>
</div>



{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    
{% block title %} Register {% endblock %}


{% block content %}
    <h3>Register</h3>

    <div class="row">
        <div class="col-4">
            <form method="POST" action="{% url 'users:register' %}">
                {% csrf_token %}
        
                {{ form | crispy }}
        
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>

    
{% endblock %}
    